//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3615
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.InvoiceManagement.ProductTypes {
    
    
    public partial class Index {
        
        /// <summary>
        /// ctlShortcuts control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CRM.Themes.ZproCRM.Shortcuts ctlShortcuts;
        
        /// <summary>
        /// ctlModuleHeader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CRM.UserControls.Migrated_ModuleHeader ctlModuleHeader;
        
        /// <summary>
        /// ctlListView control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CRM.InvoiceManagement.ProductTypes.ListView ctlListView;
    }
}
